module.exports = {
  'panel-min-width': 'var(--panel-min-width, 1280px)',
  'font-weight-bold': 'var(--font-weight-bold, 600)',
  'font-size-lg': 'var(--font-size-lg, 20px)',
  'font-size': 'var(--font-size, 18px)',
  'font-size-md': 'var(--font-size-md, 16px)',
  'font-size-sm': 'var(--font-size-sm, 14px)',
  'font-size-xs': 'var(--font-size-xs, 12px)',
  'color-theme': 'var(--color-theme, #00C4FF)',
  'color-border': 'var(--color-border, #E3E6E8)',
  'color-panel-bg': 'var(--color-panel-bg, #EFF1F4)',
  'color-panel-bg-secondary': 'var(--color-panel-bg-secondary, #F1F3F5)',
  'color-text-primary': 'var(--color-text-primary, #121A21)',
  'color-text-regular': 'var(--color-text-regular,  #34495E)',
  'color-text-secondary': 'var(--color-text-secondary, #A5ADB5)',
  'color-text-placeholder': 'var(--color-text-placeholder, #D5D9DE)',
  'color-success': 'var(--color-success, #4BCB21)',
  'color-warning': 'var(--color-success, #FFC82C)',
  'color-info': 'var(--color-success, #A5ADB5)',
  'color-white': 'var(--color-white, #ffffff)',
  // menu
  'navbar-height': 'var(--navbar-height, 48px)',
  'img-height': 'var(--img-height, 32px)',
  'title-color': 'var(--title-color, rgba(0, 0, 0, 0.87))',
  'subtitle-color': 'var(--subtitle-color, rgba(0, 0, 0, 0.54))',
  'menu-bgcolor': 'var(--menu-bgcolor, #ffffff)',
  'active-color': 'var(--active-color, rgba(0, 0, 0, 0.87))',
  'hover-color': 'var(--hover-color, rgba(0, 0, 0, 0.74))',
  'default-color': 'var(--default-color, rgba(0, 0, 0, 0.38))',
  'box-shadow-color': 'var(--box-shadow-color, rgba(0, 0, 0, 0.05))',
  // 纵向固定菜单
  'vertical-fixed-default-color': 'var(--vertical-fixed-default-color, rgba(0, 0, 0, 0.54))',
  'vertical-fixed-hover-color': 'var(--vertical-fixed-hover-color, rgba(0, 0, 0, 0.54))',
  'vertical-fixed-hover-bgcolor': 'var(--vertical-fixed-hover-bgcolor, rgba(0, 0, 0, 0.05))',
  'vertical-fixed-active-color': 'var(--vertical-fixed-active-color, #ffffff)',
  'vertical-fixed-active-bgcolor': 'var(--vertical-fixed-active-bgcolor, #4772f4)',
  'box-shadow-color-fixed': 'var(--box-shadow-color-fixed, rgba(0, 0, 0, 0.05))',
  // 纵向悬浮菜单
  'vertical-pop-default-color': 'var(--vertical-pop-default-color, rgba(0, 0, 0, 0.74))',
  'vertical-pop-hover-color': 'var(--vertical-pop-hover-color, rgba(0, 0, 0, 0.74))',
  'vertical-pop-hover-bgcolor': 'var(--vertical-pop-hover-bgcolor, rgba(0, 0, 0, 0.05))',
  'vertical-pop-active-color': 'var(--vertical-pop-active-color, #ffffff)',
  'vertical-pop-active-bgcolor': 'var(--vertical-pop-active-bgcolor, #4772f4)',
  'box-shadow-color-pop': 'var(--box-shadow-color-pop, rgba(0, 0, 0, 0.14))',
}
